/* exported maps */

const maps = [
    {
        online: Number.POSITIVE_INFINITY,
        offline: 0,
        text: "COLLECT THE ARTIFACTS.",
        data: [
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "          a  a      ",
            "                    ",
            "      @             ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        ]
    },
    {
        online: Number.POSITIVE_INFINITY,
        offline: 0,
        text: "AVOID THE GHOSTS.",
        data: [
            "                    ",
            "         @     G    ",
            "                    ",
            "                    ",
            "    ==     =====    ",
            "    =   =  =#A#=    ",
            "    =   ====###=    ",
            "    =          =    ",
            "    =          =    ",
            "    ============    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        ]
    },
    {
        online: Number.POSITIVE_INFINITY,
        offline: 0,
        text: "THIS ONE IS EASY.",
        data: [
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "       ###          ",
            "      ##A##         ",
            "      #####         ",
            "  ====#   #====     ",
            "  =####   ####=     ",
            "  =#G #   #G #=     ",
            "  =#  #   #  #=     ",
            "  =####   ####=     ",
            "  ===== @ =====     ",
            "                    ",
            "                    ",
        ]
    },
    {
        online: 4000,
        offline: 10000,
        text: "THEY WON'T HURT YOU. UNLESS...",
        data: [
            "                          ",
            "                          ",
            "                          ",
            "G    G    G    G    G     ",
            "                          ",
            "##########################",
            "                          ",
            "                          ",
            " @   a      a      a      ",
            "                          ",
            "                          ",
            "##########################",
            "                          ",
            " G    G    G    G    G    ",
            "                          ",
            "                          ",
        ]
    },
    {
        online: 5000,
        offline: 1600,
        text: "STAY WITHIN THE LINES.",
        data: [
            " @#  #  #  #  #  #  # G#  ",
            "  # G#  # G#  #G #  #  #  ",
            "####################A#####",
            "G #  #  #  # G#  # G#  # G",
            "  #  #  #  #  #  #  #  #  ",
            "#####A####################",
            "  # G#  # G#  #  #  #G #  ",
            "  #  #  #  #  #  #  #  #  ",
            "##############A###########",
            " G#  #  #  # G#  # G#  # G",
            "  #  #  #  #  #  #  #  #  ",
            "#####A###########A########",
            "  #  #  #  #  #  #  # G#  ",
            "  # G#  # G#  #  #  #  #  ",
            "##########################",
        ]
    },
];
