/* exported maps */

const maps = [
    {
        online: Number.POSITIVE_INFINITY,
        offline: 0,
        text: "COLLECT THE ARTIFACTS.",
        data: [
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "          a  a      ",
            "                    ",
            "      @             ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        ]
    },
    {
        online: Number.POSITIVE_INFINITY,
        offline: 0,
        text: "AVOID THE GHOSTS.",
        data: [
            "                    ",
            "         @     G    ",
            "                    ",
            "                    ",
            "    ==     =====    ",
            "    =   =  =#A#=    ",
            "    =   ====###=    ",
            "    =          =    ",
            "    =          =    ",
            "    ============    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        ]
    },
    {
        online: Number.POSITIVE_INFINITY,
        offline: 0,
        text: "THESE WON'T HURT YOU.",
        data: [
            "                    ",
            "                    ",
            "                    ",
            "                    ",
            "       ###          ",
            "      ##A##         ",
            "      #####         ",
            "  ====#   #====     ",
            "  =####   ####=     ",
            "  =#G #   #G #=     ",
            "  =#  #   #  #=     ",
            "  =####   ####=     ",
            "  ===== @ =====     ",
            "                    ",
            "                    ",
        ]
    },
    {
        online: 4000,
        offline: 10000,
        text: "UNLESS...",
        data: [
            "                    ",
            "G    G    G    G    ",
            "                    ",
            "                    ",
            "                    ",
            "####################",
            "                    ",
            "                    ",
            " @   a      a      a",
            "                    ",
            "                    ",
            "####################",
            "                    ",
            "                    ",
            " G    G    G    G   ",
            "                    ",
        ]
    },
   {
        online: 4000,
        offline: 2000,
        text: "KEEP GOING.",
        data: [
            "@         #####    G",
            " ###         #A     ",
            "##  ###      #####  ",
            "      ####       ###",
            "           ====    #",
            "           ==== G  A",
            "   =       ====    #",
            "  ===       a       ",
            "   =G               ",
            "         G     ##   ",
            "         ==    #G  =",
            "   ###A   =    #  ==",
            "      #   ==   #    ",
            "  G          ###   a",
            "                    ",
        ]
    },
    {
        online: 5000,
        offline: 1500,
        text: "BOO!",
        data: [
            "                    ",
            "                    ",
            "                    ",
            "    =============   ",
            "    =#        Ga=   ",
            "    =#  == ====G=   ",
            "    =#  =#A= #= =   ",
            "    =#  =#A= #= =   ",
            "    =#  == ==== =   ",
            "    =# @       a=   ",
            "    =============   ",
            "                    ",
            "                    ",
            "                    ",
            "                    ",
        ]
    },
    {
        online: 5000,
        offline: 1600,
        text: "STAY WITHIN THE LINES.",
        data: [
            "  #  #  #  #  #  #  ",
            " @# G#  # G#  #G #  ",
            "#################A##",
            "G #  #  #  # G#  # G",
            "  #  #  #  #  #  #  ",
            "#####A##############",
            "  # G#  # G#  #  #  ",
            "  #  #  #  #  #  #  ",
            "##############A#####",
            " G#  #  #  # G#  # G",
            "  #  #  #  #  #  #  ",
            "#################A##",
            "  #  #  #  #  #  #  ",
            "  # G#  # G#  #  #  ",
            "########A###########",
        ]
    },
    {
        online: Number.POSITIVE_INFINITY,
        offline: 0,
        text: "WHOA",
        data: [
            "     G G G G G G    ",
            "  G               G ",
            "                    ",
            "                    ",
            "G                   ",
            "                   G",
            "                    ",
            "G        @          ",
            "                    ",
            "                   G",
            "G                   ",
            "                    ",
            "                    ",
            "  G              G  ",
            "     G G G G G G    ",
        ]
    }
];
